Allow custom messages to be passed to error
seabasser/sea-bass-ui pull request #22
Opened 2021-08-18 19:50 UTC by aleccohan

Allow custom messages to be passed to error.

2021-08-18 20:29 UTC, ryelo requested changes

2021-08-18 20:29 UTC, ryelo commented on src/routes/Make.tsx
> +      { error && <Error drink={input} ></Error> }
```suggestion
      { error && <Error drink={input}/> }
```

2021-08-18 20:29 UTC, ryelo commented on src/utils/index.tsx
> +
can you add a `break;` here

2021-08-18 20:47 UTC, SteveHNH commented on src/utils/index.tsx
> +    return 'Drink it strait, its the fastest way to reach your goal!'
is it `strait` or `straight`?

2021-08-18 20:51 UTC, aleccohan commented on src/utils/index.tsx
> +    return 'Drink it strait, its the fastest way to reach your goal!'
🤦 Yup!  Straight

2021-08-19 12:48 UTC, ryelo approved these changes

2021-08-19 13:02 UTC, SteveHNH approved these changes

2021-08-19 13:32 UTC, merged